//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyPortal.DomainModels.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_trade_pair
    {
        public stock_trade_pair()
        {
            this.trades = new HashSet<stock_trade>();
        }
    
        public int trade_pair_id { get; set; }
        public int trade_day_id { get; set; }
        public int profit_loss { get; set; }
        public string summary { get; set; }
        public string symbol { get; set; }
        public string attachment_uri { get; set; }
        public double spread { get; set; }
        public int share { get; set; }
    
        public virtual stock_trade_day trade_day { get; set; }
        public virtual ICollection<stock_trade> trades { get; set; }
    }
}
