//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyPortal.DomainModels.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_trade_day
    {
        public stock_trade_day()
        {
            this.trade_pairs = new HashSet<stock_trade_pair>();
        }
    
        public int trade_day_id { get; set; }
        public System.DateTime trade_date { get; set; }
        public int profit_loss { get; set; }
        public string summary { get; set; }
    
        public virtual ICollection<stock_trade_pair> trade_pairs { get; set; }
    }
}
