//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyPortal.DomainModels.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class stock_trade
    {
        public int trade_id { get; set; }
        public int trade_pair_id { get; set; }
        public int type { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
        public int action { get; set; }
        public int share { get; set; }
        public double price { get; set; }
        public string summary { get; set; }
    
        public virtual stock_trade_pair trade_pair { get; set; }
    }
}
